spring.profiles: integration
  spring.data.mongodb.database:free_game_db
  spring.data.mongodb.port:27017
  spring.data.mongodb.host:localhost
  server.port:8081
---
spring.profiles: production
spring.data.mongodb.uri:System.getenv("ATLAS_URI")